version: '3'
services:

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "8000:8000"
#    volumes:
#      - ../processor:/optimus/processor
#      - ../config:/config
#      - ../enrichutils:/optimus/enrichutils
#      - ../secrets/credentials.json:/secrets/credentials.json
    environment:
      PORT: 8000
    image: "fastapi-demo:v1"
#    depends_on:
#      - postgresql
#      - elasticsearch-master